name: manual approval
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # This job runs without any approval
  job_without_approval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo "This job does not require approval" > job_output.txt

  # This job depends on the successful completion of job_without_approval
  job_needs_approval:
    needs: job_without_approval
    runs-on: ubuntu-latest
    steps:
      - name: Request manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: steja6872
          minimum-approvals: 1
          exclude-workflow-initiator-as-approver: true
          issue-title: "Need approval to run this test job"
          issue-body: |
            The job without approval output:
            '''
            $(cat job_output.txt)
            '''
      - uses: actions/checkout@v1    
      - name: Run a multi-line script
        run: |
          echo "This job needs approvals to run"
          echo "After approving job will run"
